services:
  - type: web
    name: pagador-simulator
    env: node
    buildCommand: npm install && npm run build:client
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: NOTIFICATION_SERVICE_URL
        value: https://zkslv9jlz3.execute-api.us-east-1.amazonaws.com/notifications
      - key: AWS_REGION
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_SQS_QUEUE_URL
        value: https://zkslv9jlz3.execute-api.us-east-1.amazonaws.com/notifications
    healthCheckPath: /health
