services:
  - type: web
    name: pagador-simulator
    env: node
    buildCommand: npm install && npm run build:client
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: AWS_SQS_QUEUE_URL
        value: https://au9rulweql.execute-api.us-east-1.amazonaws.com/notifications
   
    healthCheckPath: /health
